export default {
    "hp": "hp",
    "hp%": "hp_",
    "atk": "atk",
    "atk%": "atk_",
    "def%": "def_",
    "em": "eleMas",
    "er": "enerRech_",
    "cr": "critRate_",
    "cd": "critDMG_",
    "phys%": "physical_dmg_",
    "anemo%": "anemo_dmg_",
    "geo%": "geo_dmg_",
    "electro%": "electro_dmg_",
    "hydro%": "hydro_dmg_",
    "pyro%": "pyro_dmg_",
    "cryo%": "cryo_dmg_",
    "dendro%": "dendro_dmg_",
    "heal": "heal_",
    "dmg%": "all_dmg_"
} as Record<string, string>;